### ISSUE TITLE
画像の比率に制限をつける

### ISSUE THREAD

**Issue by ginjake** [rassi0429/photo.neos.love#19]
# 概要
縦に長すぎる画像を放り込むと、表示スペースが圧迫され独占できる

# スクショ
![image](https://user-images.githubusercontent.com/16838187/173505085-b19ce959-a7c5-4ad3-8222-13658cd8ae63.png)

# 放り込んだ画像
![2022-06-10 11 41 23t](https://user-images.githubusercontent.com/16838187/173505222-4d3cf2db-9879-4274-a9cd-36ed6a4d500b.png)

**Comment by rassi0429** [comment]
なおした
