### ISSUE TITLE
ワールド名にHTMLタグが使われているとき、タイトルでトリムされていない

### ISSUE THREAD

**Issue by tanossy** [rassi0429/photo.neos.love#43]
タグは手動で直せるので優先順序は低いです。
MOD側でトリムするのかサイト側でトリムするのか・・

![1](https://user-images.githubusercontent.com/107523253/174535835-f54b7384-732e-4a1e-ab6e-15efd236142c.jpg)

**Comment by rassi0429** [comment]
サイトの表示上でトリムしようと思います。
